# @name  csrf_fetch
HEAD {{sap_dev_server}}/sap/zqdrtrest/ HTTP/1.1
Authorization: Basic {{sap_dev_user}} {{sap_dev_pwd}}
X-CSRF-Token: Fetch

###

# Table Query Request with filters and aggregations
POST {{sap_dev_server}}/sap/zqdrtrest/entities/T/TADIR/queryResult HTTP/1.1
X-CSRF-Token: {{csrf_fetch.response.headers.x-csrf-Token}}
Authorization: Basic {{sap_dev_user}} {{sap_dev_pwd}}
Content-Type: application/json

{
    "filters": [
        {
            "fieldName": "object",
            "ranges": [
                {
                    "operation": "EQ",
                    "value1": "CLAS"
                }
            ]
        },
        {
            "fieldName": "obj_name",
            "ranges": [
                {
                    "operation": "StartsWith",
                    "value1": "CX"
                }
            ]
        }
    ],
    "aggregations": {
        "aggregationExpressions": [
            {
                "fieldName": "object"
            }
        ],
        "havingExpressions": [
            {
                "fieldName": "object",
                "function": "count",
                "operation": "GE",
                "value1": 18
            }
        ]
    },
    "sortFields": [
        {
            "fieldName": "object",
            "sortDirection": "Ascending"
        }
    ],
    "outputFields": [
        {
            "fieldName": "object",
            "index": 1
        }
    ]
}

###

# Table Query Request with output field with aggregation function
POST {{sap_dev_server}}/sap/zqdrtrest/entities/T/sflight/queryResult HTTP/1.1
X-CSRF-Token: {{csrf_fetch.response.headers.x-csrf-Token}}
Authorization: Basic {{sap_dev_user}} {{sap_dev_pwd}}
Content-Type: application/json

{
    "settings": {
        "maxRows": 10,
        "determineMaxRows": true,
        "readMetadata": false
    },
    "outputFields": [
        {
            "fieldName": "seatsmax",
            "function": "max"
        },
        {
            "fieldName": "seatsmax_f",
            "function": "avg"
        }
    ]
}

###

# Table Query Request with some filters
POST {{sap_dev_server}}/sap/zqdrtrest/entities/T/dd02l/queryResult HTTP/1.1
X-CSRF-Token: {{csrf_fetch.response.headers.x-csrf-Token}}
Authorization: Basic {{sap_dev_user}} {{sap_dev_pwd}}
Content-Type: application/json

{
    "settings": {
        "maxRows": 10
    },
    "filters": [
        {
            "fieldName": "tabclass",
            "ranges": [
                {
                    "operation": "EQ",
                    "value1": "TRANSP"
                }
            ]
        },
        {
            "fieldName": "tabname",
            "ranges": [
                {
                    "operation": "StartsWith",
                    "value1": "DD"
                }
            ]
        }
    ],
    "outputFields": [
        {
            "fieldName": "tabname"
        },
        {
            "fieldName": "tabclass"
        }
    ]
}

###

# Table Query Request with offset
POST {{sap_dev_server}}/sap/zqdrtrest/entities/T/TADIR/queryResult HTTP/1.1
X-CSRF-Token: {{csrf_fetch.response.headers.x-csrf-Token}}
Authorization: Basic {{sap_dev_user}} {{sap_dev_pwd}}
Content-Type: application/json

{
    "settings": {
        "maxRows": 10,
        "offset": 5000,
        "determineMaxRows": true
    },
    "filters": [
        {
            "fieldName": "object",
            "ranges": [
                {
                    "operation": "EQ",
                    "value1": "CLAS"
                }
            ]
        }
    ]
}

###

# CDS Query request with parameters and filters
POST {{sap_dev_server}}/sap/zqdrtrest/entities/c/demo_cds_parameters/queryResult HTTP/1.1
X-CSRF-Token: {{csrf_fetch.response.headers.x-csrf-Token}}
Authorization: Basic {{sap_dev_user}} {{sap_dev_pwd}}
Content-Type: application/json

{
    "settings": {
        "determineMaxRows": true
    },
    "parameters": [
        {
            "fieldName": "p_distance_l",
            "value": 1000
        },
        {
            "fieldName": "p_distance_u",
            "value": 10000
        },
        {
            "fieldName": "p_unit",
            "value": "KM"
        }
    ],
    "filters": [
        {
            "fieldName": "cityfrom",
            "ranges": [
                {
                    "operation": "StartsWith",
                    "value1": "NEW",
                    "exclude": true
                }
            ]
        }
    ]
}