import ColumnItem from "../element/ColumnItem";
import FilterItem from "../element/FilterItem";
import QuickFilter from "./QuickFilter";
import StateRegistry from "../state/StateRegistry";
import AddQuickFiltersPopover from "../helper/AddQuickFilterPopover";

import Panel from "sap/m/Panel";
import ScrollContainer from "sap/m/ScrollContainer";
import OverflowToolbar from "sap/m/OverflowToolbar";
import Button from "sap/m/Button";
import ToolbarSpacer from "sap/m/ToolbarSpacer";
import Title from "sap/m/Title";
import VerticalLayout from "sap/ui/layout/VerticalLayout";
import { ButtonType } from "sap/m/library";
import jQuery from "sap/ui/thirdparty/jquery";
import Event from "sap/ui/base/Event";
import Control from "sap/ui/core/Control";

/**
 * FilterBar with vertical orientation
 *
 * @namespace devepos.qdrt.control
 */
export default class SideFilterBar extends Panel {
    metadata = {
        properties: {},
        aggregations: {
            /**
             * Holds all columns for which filters can be created
             */
            columnItems: { type: "devepos.qdrt.element.ColumnItem", multiple: true, singularName: "columnItem" },
            /**
             * Holds the current filter items
             */
            filterItems: { type: "devepos.qdrt.element.FilterItem", multiple: true, singularName: "filterItem" }
        },
        events: {}
    };
    /**
     * Currently no custom renderer is needed
     */
    renderer = "sap.m.PanelRenderer";

    private _filterContainer: VerticalLayout;
    private _scrollContainer: ScrollContainer;

    //#region methods generated by ui5 library for metadata
    getColumnItems?(): ColumnItem[];
    setColumnItems?(items: ColumnItem[]): this;
    addColumnItem?(item: ColumnItem): this;
    getFilterItems?(): FilterItem[];
    setFilterItems?(items: FilterItem[]): this;
    addFilterItem?(item: FilterItem): this;
    //#endregion

    init(): void {
        Panel.prototype.init.call(this);
        this.setWidth("100%");
        this.setHeight("100%");
        this.setHeaderToolbar(
            new OverflowToolbar({
                content: [
                    new Title({ text: "{i18n>entity_sideFilterBar_title}" }),
                    new ToolbarSpacer(),
                    new Button({
                        icon: "sap-icon://add",
                        tooltip: "{i18n>entity_sideFilterBar_newFilter}",
                        type: ButtonType.Transparent,
                        press: (event: Event) => {
                            this._addNewFilter(event);
                        }
                    }),
                    new Button({
                        icon: "sap-icon://delete",
                        tooltip: "{i18n>entity_sideFilterBar_deleteAllFilters}",
                        type: ButtonType.Transparent,
                        press: () => {
                            this._filterContainer.removeAllContent();
                        }
                    })
                ]
            })
        );
        this._filterContainer = new VerticalLayout({
            width: "100%"
        });
        this._scrollContainer = new ScrollContainer({
            content: this._filterContainer,
            width: "100%",
            height: "100%",
            horizontal: false,
            vertical: true
        });

        this.addContent(this._scrollContainer);
    }
    onAfterRendering(event: jQuery.Event): void {
        // do custom afterRendering
        Panel.prototype.onAfterRendering.call(this, event);
    }
    onBeforeRendering(event: jQuery.Event): void {
        Panel.prototype.onBeforeRendering.call(this, event);
        // do custom beforeRendering
    }
    exit(): void {
        Panel.prototype.exit.call(this);
    }

    private async _addNewFilter(event: Event) {
        const addFiltersPopover = new AddQuickFiltersPopover(StateRegistry.getEntityState().getData());
        const selectedFilters = await addFiltersPopover.showPopover(event.getSource() as Control);
        if (selectedFilters?.length > 0) {
            for (const selectedFilter of selectedFilters) {
                this._filterContainer.addContent(this._createQuickFilter(selectedFilter));
            }
        }
    }
    private _createQuickFilter(columnName: string) {
        return new QuickFilter({ columnName });
    }
}
